### ISSUE TITLE
No file created

### ISSUE THREAD

**Issue by N6REJ** [GuillaumeFalourd/command-output-file-action#1]
I'm not sure whats going on but its not creating the file.
https://github.com/Bearsampp/.settings/runs/4566251828?check_suite_focus=true

**Comment by GuillaumeFalourd** [comment]
Hi @N6REJ , how are you doing? 

Thank you for opening this issue!

For what I observed here, the command you tried to run was:

```shell
printf .settings,Bearsampp,bearsampp.github.io,dev,login-servers-enhanced,module-adminer,module-apache,module-composer,module-consolez,module-filezilla,module-ghostscript,module-git,module-gitlist,module-imagemagick,module-mailhog,module-mariadb,module-memcached,module-mongodb,module-mysql,module-nginx,module-ngrok,module-nodejs,module-perl,module-phpmemadmin,module-phpmyadmin,module-phppgadmin,module-postgresql,module-python,module-ruby,module-svn,module-webgrind,module-websvn,module-xdc,module-yarn,modules-untouched,prerequisites,startbootstrap-clean-blog,website
```

Am I correct?

As you can see on the [action.yml file](https://github.com/GuillaumeFalourd/command-output-file-action/blob/main/action.yml), the action uses `<command-line> &> <output-file> || true` to save the output file with the command line returned.

For what I observed in the log you shared, the output.txt file has been created successfully:

![Screen Shot 2021-12-20 at 10 18 58](https://user-images.githubusercontent.com/22433243/146773253-c8b28dcc-4ca9-4440-9620-983ffa1efb93.png)

But for the file to appear on the repository, you would have to push it back to the repository at the end of the workflow steps
(for example, using a [git-commit-push](https://github.com/GuillaumeFalourd/git-commit-push) action).

Is this what you want to achieve?

**Comment by N6REJ** [comment]
yes, ideally in a single column format.

**Comment by N6REJ** [comment]
ok, I got it to save the file now :) 
but now how do I get it into single column format?
https://github.com/Bearsampp/.settings/blob/main/current-repos.md

**Comment by N6REJ** [comment]
I got it!! ty for your help.
